// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk7Dv_-X85IyoIhNR5xP8Y5a0COGXEGfU',
    appId: '1:827304863108:web:ee028b853fbd033b0929d1',
    messagingSenderId: '827304863108',
    projectId: 'my-journey-app-7191e',
    authDomain: 'my-journey-app-7191e.firebaseapp.com',
    storageBucket: 'my-journey-app-7191e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAslXc2M4Gnl2iNMXpgAj_k_WLYS1PShQo',
    appId: '1:827304863108:android:65442a8474a5253c0929d1',
    messagingSenderId: '827304863108',
    projectId: 'my-journey-app-7191e',
    storageBucket: 'my-journey-app-7191e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgPMQb0U-qGOh5QOTKMT5cSeIg0ccYx8',
    appId: '1:827304863108:ios:2276f99f9ef66fc00929d1',
    messagingSenderId: '827304863108',
    projectId: 'my-journey-app-7191e',
    storageBucket: 'my-journey-app-7191e.firebasestorage.app',
    iosClientId: '827304863108-lt1m14e8h2c7htb6tk5qof447efm2n2a.apps.googleusercontent.com',
    iosBundleId: 'com.annie.myjourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfgPMQb0U-qGOh5QOTKMT5cSeIg0ccYx8',
    appId: '1:827304863108:ios:0fd62d51ca4a517a0929d1',
    messagingSenderId: '827304863108',
    projectId: 'my-journey-app-7191e',
    storageBucket: 'my-journey-app-7191e.firebasestorage.app',
    iosClientId: '827304863108-vldmfs69h1ij6mho1ghqh2am1v97t08a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myJourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk7Dv_-X85IyoIhNR5xP8Y5a0COGXEGfU',
    appId: '1:827304863108:web:e9cd05e9c12ec93d0929d1',
    messagingSenderId: '827304863108',
    projectId: 'my-journey-app-7191e',
    authDomain: 'my-journey-app-7191e.firebaseapp.com',
    storageBucket: 'my-journey-app-7191e.firebasestorage.app',
  );
}
